ERICA-Club-Hub/Backend

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/fix.md, .github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/refactor.md
=> :memo: Chore: 하위 Issue 템플릿 생성 #0

build.gradle, src/main/java/kr/hanjari/backend/config/SwaggerConfig.java
=> 🔧 [Chore] Swagger 세팅

src/main/java/kr/hanjari/backend/BackendApplication.java, src/main/java/kr/hanjari/backend/domain/ServiceAnnouncement.java, src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java, src/main/java/kr/hanjari/backend/repository/ServiceAnnouncementRepository.java, src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementCommandService.java, src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementQueryService.java, src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementCommandServiceImpl.java, src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementQueryServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ServiceAnnouncementController.java, src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementResponseDTO.java
- 서비스 공지사항 페이지에 필요한 API 구현
- `main` 메서드에 `@EnableJpaAuditing` 추가
=> ✨ [FEATURE] 서비스 공지사항 API 구현

src/main/java/kr/hanjari/backend/web/controller/ActivityController.java, src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java, src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
- CORS 해결 -> `CrossOrigin` 애노테이션 추가
=> 🚑️ [FIX] CORS 해결  

src/main/java/kr/hanjari/backend/domain/Activity.java, src/main/java/kr/hanjari/backend/domain/Club.java, src/main/java/kr/hanjari/backend/domain/ClubRegistration.java, src/main/java/kr/hanjari/backend/domain/File.java, src/main/java/kr/hanjari/backend/repository/ClubRegistrationRepository.java, src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/controller/DocumentController.java, src/main/java/kr/hanjari/backend/web/controller/HealthCheckController.java, src/main/java/kr/hanjari/backend/web/dto/club/request/CommonClubDTO.java
- 동아리 등록 요청 -> 이를 수락하는 형태로 동아리 등록
- 동아리 등록 요청 API
- 동아리 수락 API
- club_registration 테이블이 추가되었습니다
=> ✨ [FEATURE] 동아리 등록 관련 기능 구현

src/main/java/kr/hanjari/backend/service/user/UserCommandService.java, src/main/java/kr/hanjari/backend/service/user/impl/UserCommandServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/UserController.java, src/main/java/kr/hanjari/backend/web/dto/user/response/UserLoginResponseDTO.java
=> ♻️ [REFACTOR] JWT 응답 방식 Body에서 Header로 변경  

src/main/java/kr/hanjari/backend/web/controller/HealthCheckController.java
=> :bug: [FIX] Health Check API CORS 해결 

src/main/java/kr/hanjari/backend/domain/Club.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java, src/main/resources/application.properties
- Club 일부 컬럼 null 허용으로 변경
- 동아리 등록 요청 수락 시 동아리 모집상태 기본값 모집예정으로 설정
=> 🐛 [FIX] Club 테이블 컬럼 제약조건 수정

src/main/java/kr/hanjari/backend/domain/Club.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java, src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionResponseDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentResponseDTO.java
- 동아리 소개글, 모집 안내 조회 시 작성된 내용이 없는 경우, 적절한 에러 메세지를 응답하는 방식에서 Null 값 응답하는 로직으로 변경 (프론트 요구 사항)
- 동아리 상세 정보 수정 시, 회비도 업데이트 할 수 있도록 수정
=> ♻ [REFACTOR] 동아리 소개글, 모집 안내 응답 로직 수정

docker-compose.yml
=> 👷 [CHORE] nginx 추가

src/main/java/kr/hanjari/backend/web/controller/AuthController.java
=> [FIX] 헤더 보이도록 애노테이션 옵션 추가

src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/dto/club/request/ClubScheduleListRequestDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ScheduleListResponseDTO.java
- 여러 월 별 일정 동시에 입력 가능하도록 API 로직 수정
=> ♻ [REFACTOR] 월 별 활동 생성 API 요청 값 포맷 수정

src/main/java/kr/hanjari/backend/service/auth/AuthService.java, src/main/java/kr/hanjari/backend/service/auth/impl/AuthServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/AuthController.java, src/main/java/kr/hanjari/backend/web/dto/auth/LoginResultDTO.java, src/main/java/kr/hanjari/backend/web/dto/auth/response/LoginResponseDTO.java, src/main/resources/application.properties
- 로그인 로직 조금 수정
- 로그인 API 응답 필드에 clubName 추가
- Admin -> Union Admin으로 명칭 변경
- 작업사항 1
- 작업사항 2
=> ♻️ [REFACTOR] 로그인 응답 필드 추가

src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java, src/main/java/kr/hanjari/backend/service/announcement/impl/AnnouncementServiceImpl.java
=> 🐛 [FIX] 총동연 공지사항 수정/삭제 API 문제 해결

src/main/java/kr/hanjari/backend/web/dto/club/response/ClubScheduleResponseDTO.java
-  월 별 일정 응답 DTO 변수 명 `schedules`로 통일
=> ♻️ [REFACTOR] 월 별 일정 응답 DTO 변수 명 `schedules`로 통일  

src/main/java/kr/hanjari/backend/config/SecurityConfig.java, src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRegistrationDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/GetRegistrationsResponseDTO.java
- 서비스 어드민이 사용할 등록 요청 동아리 조회 API
=> ✨ [FEATURE] 등록 요청 동아리 조회 API 구현

src/main/java/kr/hanjari/backend/config/CorsConfig.java, src/main/java/kr/hanjari/backend/config/SwaggerConfig.java, src/main/java/kr/hanjari/backend/security/token/JwtUtil.java, src/main/java/kr/hanjari/backend/service/auth/impl/AuthServiceImpl.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties
- application.properties에서 profile 활성화
- cors에 도메인 추가
- prod 설정 파일 추가
=> 👷 [CHORE] profile 설정 및 cors 변경

src/main/java/kr/hanjari/backend/config/CorsConfig.java
=> 👷 [CHORE] cors 허용 origin 수정

src/main/java/kr/hanjari/backend/config/CorsConfig.java
=> 👷 [CHORE] cors 설정 변경

src/main/java/kr/hanjari/backend/config/CorsConfig.java, src/main/java/kr/hanjari/backend/config/SwaggerConfig.java
- 문제: nginx는 http는 무조건 https로 리다이렉션, swagger는 http로 요청
- swagger에 요청 보내는 서버 명시 (https, local)
- cors 허용 오리진 localhost:4173 추가
=> 🐛 [FIX] Swagger 오류 해결

src/main/java/kr/hanjari/backend/config/CorsConfig.java, src/main/java/kr/hanjari/backend/domain/Club.java, src/main/java/kr/hanjari/backend/domain/draft/ClubDetailDraft.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java
- 동아리 상세 정보 수정 및 입력 시, 한 줄 소개 입력 값에서 삭제
=> 🐛  [FIX] 동아리 상세 정보 수정 및 입력 시, 한 줄 소개 입력 값에서 삭제

src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ActivityController.java, src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
- 동아리 등록 후 등록 요청이 삭제되도록 추가
- 쓰다만 명세서 작성
=> ✨ [FEATURE] 동아리 등록 요청 수락 API

src/main/java/kr/hanjari/backend/domain/Feedback.java, src/main/java/kr/hanjari/backend/repository/FeedbackRepository.java, src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java, src/main/java/kr/hanjari/backend/service/feedback/FeedbackService.java, src/main/java/kr/hanjari/backend/service/feedback/impl/FeedbackServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ActivityController.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/controller/DocumentController.java, src/main/java/kr/hanjari/backend/web/controller/FeedbackController.java, src/main/java/kr/hanjari/backend/web/dto/feedback/FeedbackDTO.java
=> ✨ [FEATURE] 피드백 추가

dev-docker-compose.yml, prod-docker-compose.yml
- docker-compose.yml에서 인증서 로컬 경로 수정
=> 👷 [FIX] SSL 인증서 경로 수정

src/main/java/kr/hanjari/backend/config/DevCorsConfig.java, src/main/java/kr/hanjari/backend/config/ProdCorsConfig.java
=> [CHORE] CORS 허용 도메인 추가

prod-docker-compose.yml, src/main/resources/application-prod.properties
- mysql dialect 명시
- prod-docker-compose.yml 내부 이미지명 변경
=> 🐛 [FIX] db, docker 버그 수정

src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
=> [CHORE] CORS 허용 origin 추가

src/main/java/kr/hanjari/backend/config/DevCorsConfig.java, src/main/java/kr/hanjari/backend/config/ProdCorsConfig.java
=> [CHORE] prod cors 허용 origin 제한

src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
=> [FIX] 동아리 등록 후 코드 null 해결

src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
- 등록 요청 수락 후 clubRegistration의 id를 받아오는 부분 newClub으로 변경
=> [FIX] 동아리 등록 요청 수락 오류 수정

src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
=> 👷 [CHORE] swagger용 cors 허용 origin 추가

build.gradle, src/main/resources/application.properties
=> [FEATURE] 모니터링 추가

prod-docker-compose.yml, src/main/resources/application-prod.properties, src/main/resources/application.properties
- 로그 기록 경로 명시
- prod docker에서 nginx 제거
=> ✨ [FEATURE] 로그 모니터링 추가

src/main/java/kr/hanjari/backend/domain/Activity.java, src/main/java/kr/hanjari/backend/domain/Club.java, src/main/java/kr/hanjari/backend/domain/ClubRegistration.java, src/main/java/kr/hanjari/backend/domain/Document.java, src/main/java/kr/hanjari/backend/domain/Introduction.java, src/main/java/kr/hanjari/backend/domain/Recruitment.java, src/main/java/kr/hanjari/backend/domain/Schedule.java, src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ActivityController.java, src/main/java/kr/hanjari/backend/web/dto/activity/request/UpdateActivityRequest.java
- 활동로그 수정 시 요청 방식, 처리 방식 변경
- 이미지 변경사항 x -> 내용만 수정
- 이미지 변경사항 o -> 이미지 전체 삭제 후 다시 생성
- varchar 타입 컬럼 길이 명시
=> ✨ [FEATURE] 활동로그 수정 API 변경

src/main/resources/application.properties
- SSL 충돌로 인한 properties 파일 내 ssl 옵션 추가
- X
=> [FEATURE] SSL 충돌로 인한 properties 파일 내 ssl 옵션 추가

src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java, src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java, src/main/java/kr/hanjari/backend/web/controller/ClubController.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionResponseDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubOverviewResponseDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentResponseDTO.java, src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ClubBasicInfoResponseDTO.java
- 오버뷰 정보와 기본 정보 API를 분리
- 동아리 모집 조회 시, 모집 대상도 함께 응답
- 스웨거 명세서에 해당 API `v2` 명시
=> [FEATURE] 화면 수정사항 반영

src/main/java/kr/hanjari/backend/web/dto/club/response/ClubResponseDTO.java
- 동아리 정보 조회 시, 상위 카테고리만 응답
- None
=> [Feature] 동아리 정보 조회 시, 상위 카테고리만 응답
